# This is a basic workflow to help you get started with Actions

name: PR comment workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request review comment events but only for the master branch
  pull_request_review_comment:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_webhook:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Invoke webhook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: "https://reviewmanager2022.herokuapp.com/review-store"
        webhook_secret: "1234"
        data: '{ "user_email": "${{github.event.pull_request.user.login}}", "reviewer_email": "${{github.event.comment.user.login}}",  "commit_id": "${{github.event.comment.commit_id}}", "repo_link": "${{github.event.repository.html_url}}", "comment_id": "${{github.event.comment.id}}", "comment": ${{toJson(github.event.comment.body)}} }'
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
